# Write a function mutate to compute all words generated by a single mutation on a given word. A mutation is defined as inserting a character, deleting a character, replacing a character, or swapping 2 consecutive characters in a string. For simplicity consider only letters from a to z.

def mutate(word):
    result = set()
    letters = [chr(i) for i in range(ord('a'), ord('z')+1)]
    for i in range(len(word)+1):
        if i != len(word):
            del_str = word[:i] + word[i+1:]
            result.add(del_str)
        for letter in letters:
            ins_str = word[:i] + letter + word[i:]
            result.add(ins_str)
            if i != len(word):
                rep_str = word[:i] + letter + word[i+1:]
                result.add(rep_str)
    j = 0
    k = 1
    while(k < len(word)):
        swap_str = word[:j] + word[k] + word[j] + word[k+1:]
        j += 1
        k += 1
        result.add(swap_str)
    return result
        
words = mutate('hello')
print('cello' in words)
