# Write a function nearly_equal to test whether two strings are nearly equal. Two strings a and b are nearly equal when a can be generated by a single mutation on b.

import string

def nearly_equal(word1, word2):
    letters = string.ascii_lowercase
    result = set()
    for i in range(len(word2)):
        deletion = word2[:i] + word2[i+1:]
        result.add(deletion)
        for letter in letters:
            rep_str = word2[:i] + letter + word2[i+1:]
            result.add(rep_str)
    for i in range(len(word2) + 1):
        for letter in letters:
            ins_str = word2[:i] + letter + word2[i:]
            result.add(ins_str)
    for i in range(len(word2) - 1):
        swap_str = word2[:i] + word2[i+1] + word2[i] + word2[i+2:]
        result.add(swap_str)
    result.discard(word2)
    return word1 in result

print(nearly_equal('python', 'perl'))
print(nearly_equal('perl', 'pearl'))
