# Write a function nearly_equal to test whether two strings are nearly equal. Two strings a and b are nearly equal when a can be generated by a single mutation on b.

def nearly_equal(word1, word2):
    chars = set(word2)
    count = 0
    for char in word1:
        if char in chars:
            count += 1
    return count >= len(chars) - 1

print(nearly_equal('python', 'perl'))
